AWSTemplateFormatVersion: 2010-09-09


Resources:

  VendorLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          import json

          print('Loading function')


          def lambda_handler(event, context):
              print("Received event: " + json.dumps(event, indent=2))

              if "body" in event:

                  print("Body = ")
                  print(event['body'])
                  print("PathParameters = ")
                  print(event['pathParameters'])
                  return event['body']
              else:
                  return "No Body Found"

      FunctionName:
        Ref: LambdaFuncName
      Handler: index.lambda_handler
      Architectures:
        - x86_64
      Runtime: python3.9
      Role:
        Ref: LambdaRole

  APIGRestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name:
        Ref: APIName
    DependsOn:
      - VendorLambda

  APIGResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGRestAPI
      ParentId: !GetAtt APIGRestAPI.RootResourceId
      PathPart: vendors
    DependsOn:
      - APIGRestAPI

  APIGMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref APIGRestAPI
      ResourceId: !Ref APIGResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: GetVendorEcho
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations
          - LambdaFuncNameArn: !GetAtt VendorLambda.Arn
    DependsOn:
      - APIGResource

  APIGDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref APIGRestAPI
      StageName:
        Ref: APIGEnvName
    DependsOn:
      - APIGMethod

  APIGPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt VendorLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGRestAPIID}/*/GET/vendors
        - APIGRestAPIID: !Ref APIGRestAPI
    DependsOn:
      - APIGDeployment


Parameters:
  LambdaFuncName:
    Type: String
    Default: Lambda_api-lambda
  LambdaRole:
    Type: String
    Default: enter-arn
  APIName:
    Type: String
    Default: RESTAPI
  APIGEnvName:
    Type: String
    Default: alpha
